name: Manus JP Catalog Merge

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'data/manus/jp/*.json'   # ← Manus がここに置いたら自動起動

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Merge Manus outputs into catalog_jp.json
        run: |
          python scripts/merge_catalog_jp.py

      - name: Show summary
        if: always()
        run: |
          echo "== changed files =="
          git status --porcelain
          echo
          test -f reports/merge_jp_summary.txt && cat reports/merge_jp_summary.txt || true

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(catalog_jp): merge Manus additions (auto)"
          title: "chore(catalog_jp): merge Manus additions (auto)"
          body: |
            Manus 追加分を自動マージしました。
            - data/manus/jp/ 配下の新着を取り込み
            - 既存エントリと重複照合（name/aliases/webHosts）
            - lists の和集合マージ（aliases/schemes/universalLinks/webHosts/categories）
            - `source.via = "manus"` を付与
            - 取り込み済ファイルは data/manus/jp/_processed/ へ移動
            自動生成: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          branch: manus/jp-catalog-${{ github.run_id }}
          add-paths: |
            catalog_jp.json
            data/manus/jp/_processed/**
            reports/merge_jp_summary.txt
          delete-branch: true
